/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KifusNewRouteImport } from './routes/kifus/new'
import { Route as KifusIdRouteImport } from './routes/kifus/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KifusNewRoute = KifusNewRouteImport.update({
  id: '/kifus/new',
  path: '/kifus/new',
  getParentRoute: () => rootRouteImport,
} as any)
const KifusIdRoute = KifusIdRouteImport.update({
  id: '/kifus/$id',
  path: '/kifus/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kifus/$id': typeof KifusIdRoute
  '/kifus/new': typeof KifusNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kifus/$id': typeof KifusIdRoute
  '/kifus/new': typeof KifusNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kifus/$id': typeof KifusIdRoute
  '/kifus/new': typeof KifusNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kifus/$id' | '/kifus/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kifus/$id' | '/kifus/new'
  id: '__root__' | '/' | '/kifus/$id' | '/kifus/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KifusIdRoute: typeof KifusIdRoute
  KifusNewRoute: typeof KifusNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kifus/new': {
      id: '/kifus/new'
      path: '/kifus/new'
      fullPath: '/kifus/new'
      preLoaderRoute: typeof KifusNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kifus/$id': {
      id: '/kifus/$id'
      path: '/kifus/$id'
      fullPath: '/kifus/$id'
      preLoaderRoute: typeof KifusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KifusIdRoute: KifusIdRoute,
  KifusNewRoute: KifusNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
