/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DevGalleryRouteImport } from './routes/dev-gallery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KifusNewRouteImport } from './routes/kifus/new'
import { Route as KifusIdRouteImport } from './routes/kifus/$id'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevGalleryRoute = DevGalleryRouteImport.update({
  id: '/dev-gallery',
  path: '/dev-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KifusNewRoute = KifusNewRouteImport.update({
  id: '/kifus/new',
  path: '/kifus/new',
  getParentRoute: () => rootRouteImport,
} as any)
const KifusIdRoute = KifusIdRouteImport.update({
  id: '/kifus/$id',
  path: '/kifus/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev-gallery': typeof DevGalleryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/kifus/$id': typeof KifusIdRoute
  '/kifus/new': typeof KifusNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev-gallery': typeof DevGalleryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/kifus/$id': typeof KifusIdRoute
  '/kifus/new': typeof KifusNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev-gallery': typeof DevGalleryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/kifus/$id': typeof KifusIdRoute
  '/kifus/new': typeof KifusNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev-gallery'
    | '/login'
    | '/settings'
    | '/stats'
    | '/kifus/$id'
    | '/kifus/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev-gallery'
    | '/login'
    | '/settings'
    | '/stats'
    | '/kifus/$id'
    | '/kifus/new'
  id:
    | '__root__'
    | '/'
    | '/dev-gallery'
    | '/login'
    | '/settings'
    | '/stats'
    | '/kifus/$id'
    | '/kifus/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevGalleryRoute: typeof DevGalleryRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  KifusIdRoute: typeof KifusIdRoute
  KifusNewRoute: typeof KifusNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-gallery': {
      id: '/dev-gallery'
      path: '/dev-gallery'
      fullPath: '/dev-gallery'
      preLoaderRoute: typeof DevGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kifus/new': {
      id: '/kifus/new'
      path: '/kifus/new'
      fullPath: '/kifus/new'
      preLoaderRoute: typeof KifusNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kifus/$id': {
      id: '/kifus/$id'
      path: '/kifus/$id'
      fullPath: '/kifus/$id'
      preLoaderRoute: typeof KifusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevGalleryRoute: DevGalleryRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  KifusIdRoute: KifusIdRoute,
  KifusNewRoute: KifusNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
